# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dojo', to='dojo_ninjas.Dojo'),
            preserve_default=False,
        ),
    ]
