# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
