# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20170821_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
