# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_book_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test',
        ),
    ]
