# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0003_auto_20170818_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploaded_by_id',
            new_name='uploader_id',
        ),
    ]
