# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20170817_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
        migrations.RemoveField(
            model_name='books_authors',
            name='author',
        ),
        migrations.RemoveField(
            model_name='books_authors',
            name='book',
        ),
        migrations.DeleteModel(
            name='books_authors',
        ),
        migrations.AddField(
            model_name='book_author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book_authors.Author'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_authors.Book'),
        ),
    ]
