# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20170817_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='nully', verbose_name=1000),
            preserve_default=False,
        ),
    ]
