# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0004_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='book_authors.Author'),
        ),
        migrations.DeleteModel(
            name='Book_author',
        ),
    ]
