# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='this is the defaullllt'),
            preserve_default=False,
        ),
    ]
